---
title: "SDS 291 - Homework 1"
author: "YOUR NAME HERE"
date: "TODAYS DATE"
output: pdf_document
---

```{r include=FALSE, warning=FALSE, message=FALSE, error=FALSE}
# Some customization to format the file, bring in the data you need.  Do not alter.

# knitr settings to control how R chunks work and how the pdf is compiled when knit.
require(knitr)
opts_chunk$set(
  tidy=TRUE,                     # display code as typed
  size="small",                   # slightly smaller font for code
  tidy.opts=list(width.cutoff=65), # wrap text and long comments
  fig.width=7, fig.height=5           #figure size
)
#Requiring Stat2Data package for the data
# If you're working locally on your computer, you will need to install some of these packages--see code below.
#install.packages(Stat2Data) 
require(Stat2Data)
require(mosaic)
require(tidyverse)
```

***

* Exercises to hand in:  1.19, 1.21, and 1.23 (2nd Edition)
* Due Monday, Feb 3, 2020 by 11:59AM

***

```{r}
#This brings in the dataset we need from the Stat2Data package
data("Cereal")
```

# Question 1.19

## 1.19A

```{r}

```


[DELETE THIS AND PUT YOUR ANSWER HERE]


## 1.19B

```{r}

```

<!---This question just wants you to fit the regression model, no explanation needed --->


## 1.19C

[DELETE THIS AND PUT YOUR ANSWER HERE]



# Question 1.21

## 1.21A


[DELETE THIS AND PUT YOUR ANSWER HERE]


## 1.21B

```{r}

```

[DELETE THIS AND PUT YOUR ANSWER HERE]

## 1.21C

[DELETE THIS AND PUT YOUR ANSWER HERE]




# Question 1.23

<!---This main question asks you to construct and interpret the regression models, 
     so be sure to answer with interpretation as appropriate to make sense of the figure(s) --->



## 1.23A

```{r}

```


[DELETE THIS AND PUT YOUR ANSWER HERE]


## 1.23B

```{r}

```

[DELETE THIS AND PUT YOUR ANSWER HERE]

## 1.23C

<!---The code from class generated an extra plot that we don't need, 
      This question is just asking about the second plot, the Q-Q or 
      normal probability plot --->
      
[DELETE THIS AND PUT YOUR ANSWER HERE]