\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\usepackage{hyperref}
\hypersetup{
            pdftitle={HW 8 Key},
            pdfauthor={SDS 291},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Fix footnotes in tables (requires footnote package)
\IfFileExists{footnote.sty}{\usepackage{footnote}\makesavenoteenv{longtable}}{}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother


\title{HW 8 Key}
\author{SDS 291}
\date{April 20, 2020}

\begin{document}
\maketitle

\#10.12 / 10.23

\#\#a

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Titanic}\OperatorTok{$}\NormalTok{Sex<-}\KeywordTok{relevel}\NormalTok{(Titanic}\OperatorTok{$}\NormalTok{Sex, }\DataTypeTok{ref=}\StringTok{"male"}\NormalTok{)}
\NormalTok{m1012a<-}\KeywordTok{glm}\NormalTok{(Survived}\OperatorTok{~}\NormalTok{Age}\OperatorTok{+}\NormalTok{Sex, }\DataTypeTok{data=}\NormalTok{Titanic, }\DataTypeTok{family=}\NormalTok{binomial)}
\KeywordTok{summary}\NormalTok{(m1012a)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = Survived ~ Age + Sex, family = binomial, data = Titanic)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.7541  -0.6905  -0.6504   0.7576   1.8628  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(>|z|)    
## (Intercept) -1.159839   0.219651  -5.280 1.29e-07 ***
## Age         -0.006352   0.006187  -1.027    0.305    
## Sexfemale    2.465996   0.178455  13.819  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1025.57  on 755  degrees of freedom
## Residual deviance:  795.59  on 753  degrees of freedom
##   (557 observations deleted due to missingness)
## AIC: 801.59
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\(log(odds) =\) -1.1598389 + -0.006352 age + 2.4659959 sexFemale

\(\hat\pi = \frac{e^{-1.159839+(-.006352age)+(2.465996smoker)}}{1+e^{-1.159839+(-.006352age)+(2.465996smoker)}}\)

\begin{itemize}
\tightlist
\item
  \emph{check: if fit the model and wrote out both forms of the model
  correctly}
\item
  \emph{check-minus: if didn't fit correctly and only wrote one of the
  forms of the model}
\end{itemize}

\#\#b

Age negatively associated with survival - as age increases, the log odds
of being surviving decreases, adjusting for sex - and the relationship
is no longer statistically significant.

Females have higher, and statistically significantly higher, log odds of
survival than men, adjusted for age.

\begin{itemize}
\tightlist
\item
  \emph{check-plus: they include correct and well-stated interpretations
  of odds ratios}
\item
  \emph{check: any resonable answer here that includes both direction
  and the statistical significance}
\item
  \emph{check-minus: if they don't talk about the direction \emph{and}
  statistical significance (i.e., if they only mention statistical
  significance\ldots{})}
\end{itemize}

\#\#c.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{newdata =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{Age=}\DecValTok{18}\NormalTok{, }\DataTypeTok{Sex=}\StringTok{"male"}\NormalTok{)}
\NormalTok{prob_18male<-}\KeywordTok{predict}\NormalTok{(m1012a,newdata, }\DataTypeTok{type=}\StringTok{"response"}\NormalTok{)}
\NormalTok{odds_18male<-prob_18male}\OperatorTok{/}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{prob_18male)}
\end{Highlighting}
\end{Shaded}

For a 18 year old man, the probability and odds of surviving the
Titanic:

\begin{itemize}
\item
  Probability: 0.2185435
\item
  Odds: 0.2796618
\item
  \emph{check-plus: if they (correctly) interpret the probability and
  odds in a sentence}
\item
  \emph{check: correctly calculated both}
\item
  \emph{check-minus: if they miscalculated \emph{or} only included one,
  not both}
\end{itemize}

\#\#d.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{newdata =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{Age=}\DecValTok{18}\NormalTok{, }\DataTypeTok{Sex=}\StringTok{"female"}\NormalTok{)}
\NormalTok{prob_18female<-}\KeywordTok{predict}\NormalTok{(m1012a,newdata, }\DataTypeTok{type=}\StringTok{"response"}\NormalTok{)}
\NormalTok{odds_18female<-prob_18female}\OperatorTok{/}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{prob_18female)}

\NormalTok{OR_}\DecValTok{18}\NormalTok{<-odds_18female}\OperatorTok{/}\NormalTok{odds_18male}
\end{Highlighting}
\end{Shaded}

For a 18 year old female, the probability and odds of surviving the
Titanic:

\begin{itemize}
\tightlist
\item
  Probability: 0.7670667
\item
  Odds: 3.2930744
\end{itemize}

The Odds Ratio (OR) of the odds of death for a a 18 year old woman who
smoked compared to a woman who did not smoke is:

OR: \(\frac{Odds_{females}}{Odds_{males}}\) = 11.7752038

\begin{itemize}
\tightlist
\item
  \emph{check-plus: if they (correctly) interpret the probability and
  odds in a sentence \emph{and} include the OR in a sentence}
\item
  \emph{check: correctly calculated all: odds, probability, and OR}
\item
  \emph{check-minus: if they miscalculated more than one thing, didn't
  include the OR, or only included odds but not probability}
\end{itemize}

\#\#e.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{newdata =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{Age=}\DecValTok{50}\NormalTok{, }\DataTypeTok{Sex=}\StringTok{"male"}\NormalTok{)}
\NormalTok{prob_50male<-}\KeywordTok{predict}\NormalTok{(m1012a,newdata, }\DataTypeTok{type=}\StringTok{"response"}\NormalTok{)}
\NormalTok{odds_50male<-prob_50male}\OperatorTok{/}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{prob_50male)}

\NormalTok{newdata =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{Age=}\DecValTok{50}\NormalTok{, }\DataTypeTok{Sex=}\StringTok{"female"}\NormalTok{)}
\NormalTok{prob_50female<-}\KeywordTok{predict}\NormalTok{(m1012a,newdata, }\DataTypeTok{type=}\StringTok{"response"}\NormalTok{)}
\NormalTok{odds_50female<-prob_50female}\OperatorTok{/}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{prob_50female)}

\NormalTok{OR_}\DecValTok{50}\NormalTok{<-odds_50female}\OperatorTok{/}\NormalTok{odds_50male}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lllllll@{}}
\toprule
Sex/Outcome & 18yo female & 18yo male & OR & 50yo female & 50yo male &
OR\tabularnewline
\midrule
\endhead
Probability & 0.7670667 & 0.2185435 & & 0.7288031 & 0.1858148
&\tabularnewline
Odds & 3.2930744 & 0.2796618 & 11.7752038 & 2.6873579 & 0.2282218 &
11.7752038\tabularnewline
\bottomrule
\end{longtable}

\begin{itemize}
\tightlist
\item
  \emph{check-plus: if they (correctly) interpret the probability and
  odds in a sentence}
\item
  \emph{check: correctly calculated both odds and probability for both
  males and females}
\item
  \emph{check-minus: if they miscalculated \emph{or} only included one,
  not both}
\end{itemize}

\#\#f.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\KeywordTok{coef}\NormalTok{(m1012a))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)         Age   Sexfemale 
##   0.3135367   0.9936682  11.7752038
\end{verbatim}

The odds ratio of survival for females compared to males is always the
same for all ages - this is a reflection of ``controlling for age''.

Age here is the (linear) slope and females and males just have different
intercepts; this is like the parallel slopes model we saw before in
linear regression. The slope of the lines are still parallel, so the
ratio of the odds for females compared to males is the same at all ages.

\begin{itemize}
\tightlist
\item
  \emph{check-plus: if they give an thorough answer of how and why}
\item
  \emph{check: if they say ``yes'' it will be the same at all ages
  without much explanation}
\item
  \emph{check-minus: if they reach the wrong conclusion}
\end{itemize}

\newpage

\hypertarget{recommended}{%
\section{\texorpdfstring{\textbf{RECOMMENDED}}{RECOMMENDED}}\label{recommended}}

No need to grade these \#10.13 / 10.24

\#\#a

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m1013a<-}\KeywordTok{glm}\NormalTok{(Survived}\OperatorTok{~}\NormalTok{Age}\OperatorTok{*}\NormalTok{Sex, }\DataTypeTok{data=}\NormalTok{Titanic, }\DataTypeTok{family=}\NormalTok{binomial)}
\KeywordTok{summary}\NormalTok{(m1013a)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = Survived ~ Age * Sex, family = binomial, data = Titanic)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.1262  -0.7348  -0.5194   0.7699   2.2632  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(>|z|)    
## (Intercept)   -0.298750   0.277699  -1.076    0.282    
## Age           -0.036367   0.009263  -3.926 8.63e-05 ***
## Sexfemale      0.599858   0.408050   1.470    0.142    
## Age:Sexfemale  0.065718   0.013686   4.802 1.57e-06 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1025.57  on 755  degrees of freedom
## Residual deviance:  770.56  on 752  degrees of freedom
##   (557 observations deleted due to missingness)
## AIC: 778.56
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

The addition of the interaction term changes the models for Females and
Males -- the slope for age now varies by sex.

\(log(odds)_{females} =\) -0.2987495 + -0.0363669 age + 0.5998582 smoker
+ 0.0657179 smoker:age

\(log(odds)_{females} =\) (-0.2987495 + 0.5998582) + (-0.0363669 +
0.0657179) \(\cdot age\)

\(log(odds)_{females} =\) 0.3011086 + 0.0293511 \(\cdot age\)

\(log(odds)_{males} =\) -0.2987495 + -0.0363669 \(\cdot age\)

We now have a model with different intercepts \emph{and} different
slopes, so we wouldn't expect the odds ratio between smokers and
non-smokers to be constant -- they now vary by age. We can see from the
equations above that the slope for age among smokers is now smaller that
it is for non-smokers. What we see below is that as a woman who smokes
gets older, the ratio of the odds of death between her and a similar
aged nonsmoker gets smaller.

\begin{longtable}[]{@{}lllllll@{}}
\toprule
Smoking/Outcome & 18yo female & 18yo male & OR & 50yo female & 50yo male
& OR\tabularnewline
\midrule
\endhead
Probability & 0.6962339 & 0.278211 & & 0.8542911 & 0.1074466
&\tabularnewline
Odds & 2.2920065 & 0.3854465 & 8.2383736 & 5.8629996 & 0.1203812 &
54.566625\tabularnewline
\bottomrule
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\KeywordTok{coef}\NormalTok{(m1013a))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   (Intercept)           Age     Sexfemale Age:Sexfemale 
##     0.7417452     0.9642865     1.8218604     1.0679254
\end{verbatim}

\emph{-0.5 if don't illustrate multiple models } \emph{-0.5 if no
explanation of how the interaction term changed the OR}

\#\#b

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{newtitanic<-Titanic }\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(Age) }\OperatorTok{&}\StringTok{ }\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(Sex))}
\NormalTok{mSex<-}\KeywordTok{glm}\NormalTok{(Survived}\OperatorTok{~}\NormalTok{Sex, }\DataTypeTok{data=}\NormalTok{newtitanic, }\DataTypeTok{family=}\NormalTok{binomial)}
\KeywordTok{anova}\NormalTok{(mSex,m1013a, }\DataTypeTok{test =} \StringTok{"Chisq"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Deviance Table
## 
## Model 1: Survived ~ Sex
## Model 2: Survived ~ Age * Sex
##   Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    
## 1       754     796.64                          
## 2       752     770.56  2   26.088 2.163e-06 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

We can reject the null hypothesis that \(\hat\beta_2=\hat\beta_4=0\),
since the \(\chi^2\) statistic is large (and above the critical value of
6) and the p-value is small (p\textless{}0.001) and conclude that
adjusting for age and letting the relationship between age and survival
differ between males and females does a better job of estimating the
log(odds) of death than the simple regression model with just sex alone.

\emph{-0.5 if misestimated (it's fine if the order of models are
switched and the test statistic is negative) } \emph{-0.5 if compared to
the model from 10.12 with sex and age instead of a different model with
just sex}

\#10.19 / 10.31 \#\#a

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{newtitanic2<-Titanic }\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(PClass}\OperatorTok{!=}\StringTok{"*"}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{Surv_fct=}\KeywordTok{as.factor}\NormalTok{(Survived), }
    \DataTypeTok{PClass2=}\KeywordTok{as.factor}\NormalTok{(PClass))}
\NormalTok{newtitanic2}\OperatorTok{$}\NormalTok{Surv_fct<-}\KeywordTok{relevel}\NormalTok{(newtitanic2}\OperatorTok{$}\NormalTok{Surv_fct, }\DataTypeTok{ref=}\StringTok{"1"}\NormalTok{)}
\NormalTok{gmodels}\OperatorTok{::}\KeywordTok{CrossTable}\NormalTok{(newtitanic2}\OperatorTok{$}\NormalTok{PClass, newtitanic2}\OperatorTok{$}\NormalTok{Surv_fct, }
  \DataTypeTok{prop.r=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{prop.c=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{prop.chisq =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{prop.t =} \OtherTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## |           N / Row Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  1312 
## 
##  
##                    | newtitanic2$Surv_fct 
## newtitanic2$PClass |         1 |         0 | Row Total | 
## -------------------|-----------|-----------|-----------|
##                1st |       193 |       129 |       322 | 
##                    |     0.599 |     0.401 |     0.245 | 
## -------------------|-----------|-----------|-----------|
##                2nd |       119 |       160 |       279 | 
##                    |     0.427 |     0.573 |     0.213 | 
## -------------------|-----------|-----------|-----------|
##                3rd |       138 |       573 |       711 | 
##                    |     0.194 |     0.806 |     0.542 | 
## -------------------|-----------|-----------|-----------|
##       Column Total |       450 |       862 |      1312 | 
## -------------------|-----------|-----------|-----------|
## 
## 
\end{verbatim}

We see that the proportion of survival is highest among 1st Class
passengers. 2nd and 3rd class passengers have lower odds of survival,
likely based on their further distance from the lifeboats.

\emph{-0.5 if probabilities are miscalculated } \emph{-0.5 if no
explanation of the results in the context of the problem}

\#\#b

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gmodels}\OperatorTok{::}\KeywordTok{CrossTable}\NormalTok{(newtitanic2}\OperatorTok{$}\NormalTok{PClass, newtitanic2}\OperatorTok{$}\NormalTok{Surv_fct, }
  \DataTypeTok{prop.r=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{prop.c=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{prop.chisq =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{prop.t =} \OtherTok{FALSE}\NormalTok{,}
  \DataTypeTok{chisq =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## |           N / Row Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  1312 
## 
##  
##                    | newtitanic2$Surv_fct 
## newtitanic2$PClass |         1 |         0 | Row Total | 
## -------------------|-----------|-----------|-----------|
##                1st |       193 |       129 |       322 | 
##                    |     0.599 |     0.401 |     0.245 | 
## -------------------|-----------|-----------|-----------|
##                2nd |       119 |       160 |       279 | 
##                    |     0.427 |     0.573 |     0.213 | 
## -------------------|-----------|-----------|-----------|
##                3rd |       138 |       573 |       711 | 
##                    |     0.194 |     0.806 |     0.542 | 
## -------------------|-----------|-----------|-----------|
##       Column Total |       450 |       862 |      1312 | 
## -------------------|-----------|-----------|-----------|
## 
##  
## Statistics for All Table Factors
## 
## 
## Pearson's Chi-squared test 
## ------------------------------------------------------------
## Chi^2 =  172.5191     d.f. =  2     p =  3.45104e-38 
## 
## 
## 
\end{verbatim}

\(H_0\): There is no relationship between PClass and Survival. \(H_A\):
There is a relationship between PClass and Survival.

Since the \(\chi^2\) test statistic large (172.519) and the p-value is
\textless{}0.001, we can reject the null hypothesis and conclude that
there is a relationship between PClass and Survival.

\emph{-0.5 if no hypotheses are mentioned }

\#\#c

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m1019c<-}\KeywordTok{glm}\NormalTok{(Survived}\OperatorTok{~}\NormalTok{PClass2, }\DataTypeTok{data=}\NormalTok{newtitanic2, }\DataTypeTok{family=}\NormalTok{binomial)}
\KeywordTok{summary}\NormalTok{(m1019c)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = Survived ~ PClass2, family = binomial, data = newtitanic2)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.3526  -0.6569  -0.6569   1.0118   1.8108  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(>|z|)    
## (Intercept)   0.4029     0.1137   3.543 0.000396 ***
## PClass22nd   -0.6989     0.1661  -4.208 2.58e-05 ***
## PClass23rd   -1.8265     0.1481 -12.335  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1687.2  on 1311  degrees of freedom
## Residual deviance: 1514.1  on 1309  degrees of freedom
## AIC: 1520.1
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\KeywordTok{coef}\NormalTok{(m1019c))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)  PClass22nd  PClass23rd 
##   1.4961240   0.4971179   0.1609744
\end{verbatim}

The odds of surviving for a passenger in 1st class is 1.5 to 1. These
odds are significantly greater than 0.

The odds of surviving for a passenger in 2nd class is 0.5 times (i.e.,
lower) than for 1st Class passengers. This difference was statistically
significant, as evidenced by the z statistic\textgreater{}1.96 and the
p-value\textless{}0.05.

The odds of surviving for a passenger in 3rd class is 0.16 times (i.e.,
lower) than for 1st Class passengers.

\emph{-0.5 if miscalculated (if PClass* is the reference, and all three
PClass variables are in the model) } \emph{-0.5 if no interpretation}

\#\#d

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m1019c_1st<-}\KeywordTok{coef}\NormalTok{(m1019c)[}\DecValTok{1}\NormalTok{]}
\NormalTok{m1019c_2nd<-}\KeywordTok{coef}\NormalTok{(m1019c)[}\DecValTok{2}\NormalTok{]}
\NormalTok{m1019c_3rd<-}\KeywordTok{coef}\NormalTok{(m1019c)[}\DecValTok{3}\NormalTok{]}


\NormalTok{newdata_1st =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{PClass2=}\StringTok{"1st"}\NormalTok{)}
\NormalTok{prob_1st<-}\KeywordTok{predict}\NormalTok{(m1019c,newdata_1st, }\DataTypeTok{type=}\StringTok{"response"}\NormalTok{)}
\NormalTok{odds_1st<-prob_1st}\OperatorTok{/}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{prob_1st)}

\NormalTok{newdata_2nd =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{PClass2=}\StringTok{"2nd"}\NormalTok{)}
\NormalTok{prob_2nd<-}\KeywordTok{predict}\NormalTok{(m1019c,newdata_2nd, }\DataTypeTok{type=}\StringTok{"response"}\NormalTok{)}
\NormalTok{odds_2nd<-prob_2nd}\OperatorTok{/}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{prob_2nd)}

\NormalTok{newdata_3rd =}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{PClass2=}\StringTok{"3rd"}\NormalTok{)}
\NormalTok{prob_3rd<-}\KeywordTok{predict}\NormalTok{(m1019c,newdata_3rd, }\DataTypeTok{type=}\StringTok{"response"}\NormalTok{)}
\NormalTok{odds_3rd<-prob_3rd}\OperatorTok{/}\NormalTok{(}\DecValTok{1}\OperatorTok{-}\NormalTok{prob_3rd)}

\NormalTok{OR_2nd<-odds_2nd}\OperatorTok{/}\NormalTok{odds_1st}

\NormalTok{OR_3rd<-odds_3rd}\OperatorTok{/}\NormalTok{odds_1st}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}llllll@{}}
\toprule
Smoking/Outcome & 1st Class & 2nd Class & OR & 3rd Class &
OR\tabularnewline
\midrule
\endhead
Probability & 0.5993789 & 0.4265233 & & 0.1940928 &\tabularnewline
Odds & 1.496124 & 0.74375 & 0.4971179 & 0.2408377 &
0.1609744\tabularnewline
\bottomrule
\end{longtable}

We get the same fitted probabilities from the model than we do from the
table in \#9.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{gmodels}\OperatorTok{::}\KeywordTok{CrossTable}\NormalTok{(newtitanic2}\OperatorTok{$}\NormalTok{PClass, newtitanic2}\OperatorTok{$}\NormalTok{Surv_fct, }
  \DataTypeTok{prop.r=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{prop.c=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{prop.chisq =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{prop.t =} \OtherTok{FALSE}\NormalTok{,}
  \DataTypeTok{chisq =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## |           N / Row Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  1312 
## 
##  
##                    | newtitanic2$Surv_fct 
## newtitanic2$PClass |         1 |         0 | Row Total | 
## -------------------|-----------|-----------|-----------|
##                1st |       193 |       129 |       322 | 
##                    |     0.599 |     0.401 |     0.245 | 
## -------------------|-----------|-----------|-----------|
##                2nd |       119 |       160 |       279 | 
##                    |     0.427 |     0.573 |     0.213 | 
## -------------------|-----------|-----------|-----------|
##                3rd |       138 |       573 |       711 | 
##                    |     0.194 |     0.806 |     0.542 | 
## -------------------|-----------|-----------|-----------|
##       Column Total |       450 |       862 |      1312 | 
## -------------------|-----------|-----------|-----------|
## 
##  
## Statistics for All Table Factors
## 
## 
## Pearson's Chi-squared test 
## ------------------------------------------------------------
## Chi^2 =  172.5191     d.f. =  2     p =  3.45104e-38 
## 
## 
## 
\end{verbatim}

\emph{-0.5 if miscalculated if they don't match }

\#\#e

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{anova}\NormalTok{(m1019c, }\DataTypeTok{test=}\StringTok{"Chisq"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Deviance Table
## 
## Model: binomial, link: logit
## 
## Response: Survived
## 
## Terms added sequentially (first to last)
## 
## 
##         Df Deviance Resid. Df Resid. Dev  Pr(>Chi)    
## NULL                     1311     1687.2              
## PClass2  2   173.14      1309     1514.1 < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

Yes, it does match the answer from above.

\emph{-0.5 if they don't calculate this correctly}

\end{document}
