main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Readings
    url: /reading/
    weight: 3
  - name: Assignments
    url: /assignment/
    weight: 4
  - name: Classes
    url: /class/
    weight: 5
  - name: Group Project
    url: /group/
    weight: 6
  - name: Blog
    url: /blog/
    weight: 7
  - name: Resources
    url: /resources/
    weight: 8
  - name: '<i class="fab fa-r-project"></i>'
    url: https://rstudio.smith.edu/
    weight: 9
  - name: '<i class="fab fa-slack"></i>'
    url: "http://sds291-spring2020.slack.com"
    weight: 10
assignment:
  - name: Assignments
    weight: 1
  - name: Problem sets
    weight: 2
  - name: Take Home Exams
    weight: 3
  - name: Quizes
    weight: 4
  - name: Other projects & Work
    weight: 5
group:
  - name: Introduction
    weight: 1
  - name: Group Formation
    weight: 2
  - name: Topic Selection
    weight: 3
  - name: IPUMS Data
    weight: 4
  - name: Data Extract and Analysis Plan
    weight: 5
  - name: Data Appendix
    weight: 6
  - name: Draft Results
    weight: 7
  - name: Poster
    weight: 8
  - name: Final Report
    weight: 9
resources:
  - name: R and RStudio
    weight: 1
  - name: Textbook
    weight: 2
  - name: Archived Course Materials
    weight: 3