---
title: Chapter 1
date: "2020-01-27"
menu:
  resources:
    parent: Texbook
    weight: 2
type: docs
weight: 1
output:
  blogdown::html_page:
      toc: TRUE
---

In an effort to spend more time explaining the `R` syntax we're using in this class and to connect what those tasks are with the examples from the book, I'll generate videos that walk through how to create the same models, figures, and statistical output that the textbook includes.

Note that these are based on the 2nd Edition of the data. The principles and steps are very similar for the 1st edition. For example, the 2nd edition uses Honda Accord prices, while the 1st edition used Porsche prices. 1st edition users can still use the `PorschePrice` data from the `Stat2Data` package.

# RMarkdown

Here is a quick video overview of what's going on in an  RMarkdown file using the Smith College server.

{{< youtube KCKDULGkPbI>}}


# Chapter 1

## 1.1 - Examples in 3 parts

### Part 1 - Example 1.1: Loading and Printing the Data

{{< youtube F_tGm-Aj-4M >}}

### Part 2 - Example 1.2: Making a Scatterplot

{{< youtube O_oE3xfDOyE >}}

### Part 3 - Example 1.3: Fitting a Regression Model

{{< youtube A24FVWmrzVI >}}

## 1.3 - Assessing Conditions

{{< youtube MAoN73IeNto >}}
