---
title: General Course Resources
date: "2020-01-27"
menu:
  resources:
    parent: Resources
    weight: 1
type: docs
weight: 2
output:
  blogdown::html_page:
      toc: TRUE
---

# Textbook and related resources   

- [Stat2](http://www.macmillanlearning.com/catalog/Product/stat2-cannon)
    - The book is available for purchase and rental at the bookstore or at Amazon (including a kindle version that works just fine -- just be careful when copying and pasting text from the book, some characters aren't readable by R and will throw some error). You do not need the book's Online Access
    
# RStudio

- Choose one of two options to use RStudio:
    - Log on to the Smith College [RStudio Server](http://rstudio.smith.edu).
    - Use RStudio locally:
      - Download and instal [RStudio Desktop](http://www.rstudio.com/products/rstudio/)
      - Download and install the following packages: `install.packages=c("Stat2Data","tidyverse", "mosaic")`
      

#Quantitative Resources on Campus

- [Statistics TAs](http://www.smith.edu/qlc/tutoring.html#S2) are available Sunday through Thursday from 7-9 pm in Sabin-Reed 301


# Refresher on introductory statistics

There are a few, great open-access (i.e., free!) textbooks that I encourage you to refer to revisit some core concepts from introductory statistics

- [OpenIntro with Randomization](http://www.openintro.org/stat/index.php?stat_book=isrs), most helpfully in a [pdf version](http://www.openintro.org/download.php?file=isrs1&amp;referrer=/stat/textbook.php) 

- [Modern Dive](https://moderndive.com/) by (SDS Professor) Albert Kim & Chester Ismay