\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\usepackage{hyperref}
\hypersetup{
            pdftitle={Multiple Logistic Regression - Suggested Solutions},
            pdfauthor={SDS 291},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother


\title{Multiple Logistic Regression - \emph{Suggested Solutions}}
\author{SDS 291}
\date{April 15, 2020}

\begin{document}
\maketitle

We're going to work with the \texttt{Whickham} data contains
observations about women, and whether they were alive 20 years after
their initial observation (\texttt{outcome} is a 2 level factor variable
- Alive/Dead). You can learn more about these data from the
\texttt{mosaicData} help feature if you'd like.

Specifically, we're interested in: the association of age, smoking
status (smoker), and 20-year survival (outcome: alive (success), dead
(reference / failure)). Bring in the relevant packages and the data
(below, from the mosaic package).

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(mosaic)}
\KeywordTok{library}\NormalTok{(tidyverse)}
\KeywordTok{data}\NormalTok{(}\StringTok{"Whickham"}\NormalTok{)}
\NormalTok{Whickham}\OperatorTok{$}\NormalTok{outcome<-}\KeywordTok{relevel}\NormalTok{(Whickham}\OperatorTok{$}\NormalTok{outcome, }\DataTypeTok{ref=}\StringTok{"Dead"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\newpage

\hypertarget{age-and-outcome}{%
\section{Age and Outcome}\label{age-and-outcome}}

\includegraphics{20-inclasslab-answers_files/figure-latex/unnamed-chunk-3-1.pdf}
\includegraphics{20-inclasslab-answers_files/figure-latex/unnamed-chunk-3-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m0<-}\KeywordTok{glm}\NormalTok{(outcome}\OperatorTok{~}\NormalTok{age, }\DataTypeTok{data=}\NormalTok{Whickham, }\DataTypeTok{family=}\NormalTok{binomial)}
\KeywordTok{summary}\NormalTok{(m0)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = outcome ~ age, family = binomial, data = Whickham)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.2296  -0.4277   0.2293   0.5538   1.8953  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(>|z|)    
## (Intercept)  7.403126   0.403522   18.35   <2e-16 ***
## age         -0.121861   0.006941  -17.56   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1560.32  on 1313  degrees of freedom
## Residual deviance:  946.51  on 1312  degrees of freedom
## AIC: 950.51
## 
## Number of Fisher Scoring iterations: 6
\end{verbatim}

\textbf{1. Write the fitted equation and interpret the results (in these
units) in light of the question. Be sure to comment on the magnitude and
direction of the association.}

\(logit(survival) = \hat\beta_0 + \hat\beta_1 Age\)

\(log(odds)=\) 7.403 + -0.122\(\cdot \text{age}\)

The direction is negative, as reflected by the negative \(\beta_1\) - as
age increases, the log odds of survival decreases. For every 1
additional year of age, the log(odds) of being dead 20 years later
decreases, on average, by -0.122. The magnitude of the association seems
small, though it's really difficult to tell on the log(odds) scale since
it's not a very intuitive set of units.

\vspace{0.25in}

\textbf{2. Based on this model, what is the probability that a 60 year
old was alive 20 years after the initial survey?}

There are (at least) three ways to calculate this answer.

\hypertarget{you-could-do-the-math-yourself}{%
\subsubsection{You could do the math
yourself:}\label{you-could-do-the-math-yourself}}

\hypertarget{log-odds}{%
\paragraph{log odds}\label{log-odds}}

\(log(odds)=\) 7.403 + -0.122\(\cdot \text{60}\) = 7.403 + -7.312 =
0.091

\hypertarget{odds}{%
\paragraph{odds}\label{odds}}

\(\widehat{odds}= e^{log(odds)}\) = exp(0.091) = 1.096

\hypertarget{probability}{%
\paragraph{probability}\label{probability}}

\(\hat\pi=\) 1.096 / (1 + 1.096) = 1.096 / 2.096 = 0.523

For the two that use \texttt{R} to do the calculation, you have to
define a value for age - here, it's 60 - so that it knows by what to
multiply the \(\hat\beta_1\) coefficient.

\hypertarget{use-the-predict-function}{%
\subsubsection{\texorpdfstring{Use the \texttt{predict()}
function}{Use the predict() function}}\label{use-the-predict-function}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{newdata <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{age=}\DecValTok{60}\NormalTok{)}
\KeywordTok{predict}\NormalTok{(m0, newdata, }\DataTypeTok{type=}\StringTok{"response"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         1 
## 0.5228436
\end{verbatim}

\hypertarget{program-the-math-yourself}{%
\subsubsection{Program the math
yourself}\label{program-the-math-yourself}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#define age}
\NormalTok{age<-}\DecValTok{60}
\CommentTok{#calculate the log odds from the saved coefficient}
\NormalTok{logodds<-}\KeywordTok{coef}\NormalTok{(m0)[}\DecValTok{1}\NormalTok{]}\OperatorTok{+}\StringTok{ }\NormalTok{(}\KeywordTok{coef}\NormalTok{(m0)[}\DecValTok{2}\NormalTok{]}\OperatorTok{*}\NormalTok{age)}
\CommentTok{#put them together in a data frame}
\NormalTok{m0_data<-}\KeywordTok{as.data.frame}\NormalTok{(}\KeywordTok{cbind}\NormalTok{(age,logodds))}
\CommentTok{#Calculate the odds and probability}
\NormalTok{m0_data <-}\StringTok{ }\NormalTok{m0_data }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{odds=}\KeywordTok{exp}\NormalTok{(logodds),}
        \DataTypeTok{prob =}\NormalTok{ odds}\OperatorTok{/}\NormalTok{(}\DecValTok{1}\OperatorTok{+}\NormalTok{odds))}
\CommentTok{#Report back out the odds and predicted values }
\NormalTok{m0_data}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   age    logodds     odds      prob
## 1  60 0.09143792 1.095749 0.5228436
\end{verbatim}

\vspace{0.25in}

\hypertarget{smoking-status-and-outcome-alive}{%
\section{Smoking Status and Outcome
(Alive)}\label{smoking-status-and-outcome-alive}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Whickham}\OperatorTok{$}\NormalTok{smoker<-}\KeywordTok{factor}\NormalTok{(Whickham}\OperatorTok{$}\NormalTok{smoker, }\DataTypeTok{levels=}\KeywordTok{c}\NormalTok{(}\StringTok{"Yes"}\NormalTok{, }\StringTok{"No"}\NormalTok{))}
\NormalTok{Whickham}\OperatorTok{$}\NormalTok{outcome<-}\KeywordTok{factor}\NormalTok{(Whickham}\OperatorTok{$}\NormalTok{outcome, }\DataTypeTok{levels=}\KeywordTok{c}\NormalTok{(}\StringTok{"Alive"}\NormalTok{, }\StringTok{"Dead"}\NormalTok{))}
\KeywordTok{tally}\NormalTok{(}\OperatorTok{~}\StringTok{ }\NormalTok{smoker }\OperatorTok{+}\StringTok{ }\NormalTok{outcome, }\DataTypeTok{margins=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{data=}\NormalTok{Whickham)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       outcome
## smoker Alive Dead
##    Yes   443  139
##    No    502  230
\end{verbatim}

\vspace{0.25in}

\textbf{3. Calculate the Odds Ratio of smokers being alive in 20 years
compared to non-smokers from the table above.}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#OR<-(success/failure)/(success/failure)}
\NormalTok{OR<-(}\DecValTok{443}\OperatorTok{/}\DecValTok{139}\NormalTok{)}\OperatorTok{/}\NormalTok{(}\DecValTok{502}\OperatorTok{/}\DecValTok{230}\NormalTok{)}
\NormalTok{OR}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.460202
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Whickham}\OperatorTok{$}\NormalTok{smoker<-}\KeywordTok{relevel}\NormalTok{(Whickham}\OperatorTok{$}\NormalTok{smoker, }\DataTypeTok{ref=} \StringTok{"No"}\NormalTok{)}
\NormalTok{Whickham}\OperatorTok{$}\NormalTok{outcome<-}\KeywordTok{relevel}\NormalTok{(Whickham}\OperatorTok{$}\NormalTok{outcome, }\DataTypeTok{ref=} \StringTok{"Dead"}\NormalTok{)}
\NormalTok{m1<-}\KeywordTok{glm}\NormalTok{(outcome}\OperatorTok{~}\NormalTok{smoker, }\DataTypeTok{data=}\NormalTok{Whickham, }\DataTypeTok{family=}\NormalTok{binomial)}
\KeywordTok{summary}\NormalTok{(m1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = outcome ~ smoker, family = binomial, data = Whickham)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.6923  -1.5216   0.7388   0.8685   0.8685  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(>|z|)    
## (Intercept)  0.78052    0.07962   9.803  < 2e-16 ***
## smokerYes    0.37858    0.12566   3.013  0.00259 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1560.3  on 1313  degrees of freedom
## Residual deviance: 1551.1  on 1312  degrees of freedom
## AIC: 1555.1
## 
## Number of Fisher Scoring iterations: 4
\end{verbatim}

\vspace{0.25in}

\textbf{4. Show that you can calculate the coefficient for smoking
status from your regression model as you did in \#3.}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\KeywordTok{coef}\NormalTok{(m1))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)   smokerYes 
##    2.182609    1.460202
\end{verbatim}

We estimate that smokers have 1.46 times the odds of 20-year survival
than non-smokers.

\vspace{0.25in}

\textbf{5. Based on your model, what's the probability that a smoker was
alive 20 years later?}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{smoker <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{smoker=}\StringTok{"Yes"}\NormalTok{)}
\KeywordTok{predict}\NormalTok{(m1, smoker, }\DataTypeTok{type=}\StringTok{"response"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         1 
## 0.7611684
\end{verbatim}

or manually:

\(\hat\pi=\) 3.187 / (1 + 3.187) = 3.187 / 4.187 = 0.761

\vspace{0.25in}

\textbf{6. Based on what you know about the risk of death for age and
smoking status, do these results make sense? Explain your answer.}

This doesn't make a lot of sense -- we know that smoking is bad for your
health, so it is strange that smokers have a higher odds of survival.

It might be that age counfounds this association -- younger or older
women may be more likely to be smoking, and age is related to survival.

Incidentally, we could visualize this if you wanted to see:

\includegraphics{20-inclasslab-answers_files/figure-latex/unnamed-chunk-12-1.pdf}
\includegraphics{20-inclasslab-answers_files/figure-latex/unnamed-chunk-12-2.pdf}

It seems like the younger women are the smokers, which could explain why
the coefficient is positive (on the log odds scale) or that the odds of
survival is higer for smokers than non-smokers. It isn't that smokers
are more likely to live longers, it's that all the smokers are
\emph{younger}.

\vspace{0.5in}

\hypertarget{multiple-logistic-regression}{%
\subsection{Multiple Logistic
Regression}\label{multiple-logistic-regression}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m2<-}\KeywordTok{glm}\NormalTok{(outcome}\OperatorTok{~}\NormalTok{age}\OperatorTok{+}\NormalTok{smoker, }\DataTypeTok{data=}\NormalTok{Whickham, }\DataTypeTok{family=}\NormalTok{binomial)}
\KeywordTok{summary}\NormalTok{(m2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = outcome ~ age + smoker, family = binomial, data = Whickham)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.2795  -0.4381   0.2228   0.5458   1.9581  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(>|z|)    
## (Intercept)  7.599221   0.441231  17.223   <2e-16 ***
## age         -0.123683   0.007177 -17.233   <2e-16 ***
## smokerYes   -0.204699   0.168422  -1.215    0.224    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1560.32  on 1313  degrees of freedom
## Residual deviance:  945.02  on 1311  degrees of freedom
## AIC: 951.02
## 
## Number of Fisher Scoring iterations: 6
\end{verbatim}

\vspace{0.25in}

\textbf{7. What is the odds ratio for smokers compared to non-smokers in
this model? Interpret in a sentence in the context of this real-world
problem.}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{exp}\NormalTok{(}\KeywordTok{coef}\NormalTok{(m2))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  (Intercept)          age    smokerYes 
## 1996.6405099    0.8836598    0.8148925
\end{verbatim}

When adjusting for age, the odds of 20-year survival for a smoker are
0.815 times that of a non-smoker. This direction makes more sense based
on what we know about smoking: smoking is associated with a \emph{lower}
odds of 20-year survival than non-smokers, after controlling for age.

\vspace{0.25in}

\textbf{8. What is the probability of a 60 year old non-smoker being
alive 20 years later?}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{smoker60 <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{smoker=}\StringTok{"Yes"}\NormalTok{, }\DataTypeTok{age=}\DecValTok{60}\NormalTok{)}
\KeywordTok{predict}\NormalTok{(m2, smoker60, }\DataTypeTok{type=}\StringTok{"response"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         1 
## 0.4933833
\end{verbatim}

or manually:

\(\hat\pi=\) 0.974 / (1 + 0.974) = 0.974 / 1.974 = 0.493

\textbf{9. What is the probability of a 40 year old smoker being alive
20 years later?}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nonsmoker40 <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{smoker=}\StringTok{"No"}\NormalTok{, }\DataTypeTok{age=}\DecValTok{40}\NormalTok{)}
\KeywordTok{predict}\NormalTok{(m2, nonsmoker40, }\DataTypeTok{type=}\StringTok{"response"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         1 
## 0.9341277
\end{verbatim}

or manually:

\(\hat\pi=\) 14.181 / (1 + 14.181) = 14.181 / 15.181 = 0.934

\vspace{0.25in}

\textbf{10. What does this model help us to understand about our simple
logistic regression estimates above?}

It confirms the idea that the association between smoking and survival
was confounded by age. Controlling for age made the direction of the
association what we would have expected, and that the association
between smoking and survival is no longer statistically significant
speaks to the strength of the relationship between age and survival --
it sort of superceded the association between smoking and survival that
we saw in simple logistic regression models.

\vspace{0.5in}

\hypertarget{optional---interaction-term}{%
\subsubsection{\texorpdfstring{\emph{Optional} - Interaction
Term}{Optional - Interaction Term}}\label{optional---interaction-term}}

\vspace{0.25in}

\textbf{11. What would an interaction term between age and smoking
status do in this model? How would an interaction term affect the OR for
age?}

Similar to interaction terms in linear regression, the interaction
introduces a different slope for smokers and non-smokers. In other
words, the relationship between age and survival could be stronger /
steeper in slope for smokers than for non-smokers.

\vspace{0.25in}

\textbf{12. How do the coefficients in the interaction model relate to
the separate models for Age for smokers and non-smokers (below)?}

\hypertarget{interaction}{%
\paragraph{Interaction}\label{interaction}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m3<-}\KeywordTok{glm}\NormalTok{(outcome}\OperatorTok{~}\NormalTok{age}\OperatorTok{+}\NormalTok{smoker}\OperatorTok{+}\NormalTok{age}\OperatorTok{*}\NormalTok{smoker, }\DataTypeTok{data=}\NormalTok{Whickham, }\DataTypeTok{family=}\NormalTok{binomial)}
\KeywordTok{summary}\NormalTok{(m3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = outcome ~ age + smoker + age * smoker, family = binomial, 
##     data = Whickham)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.3983  -0.4256   0.2163   0.5598   1.9283  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(>|z|)    
## (Intercept)    8.169231   0.606600  13.467   <2e-16 ***
## age           -0.133231   0.009953 -13.386   <2e-16 ***
## smokerYes     -1.457843   0.837232  -1.741   0.0816 .  
## age:smokerYes  0.022235   0.014495   1.534   0.1250    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1560.32  on 1313  degrees of freedom
## Residual deviance:  942.68  on 1310  degrees of freedom
## AIC: 950.68
## 
## Number of Fisher Scoring iterations: 6
\end{verbatim}

\hypertarget{smokers}{%
\paragraph{Smokers}\label{smokers}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Whickham_smoker<-}\StringTok{ }\NormalTok{Whickham }\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(smoker}\OperatorTok{==}\StringTok{"Yes"}\NormalTok{)}
\NormalTok{m3_smoker<-}\KeywordTok{glm}\NormalTok{(outcome}\OperatorTok{~}\NormalTok{age, }\DataTypeTok{data=}\NormalTok{Whickham_smoker, }\DataTypeTok{family=}\NormalTok{binomial)}
\KeywordTok{summary}\NormalTok{(m3_smoker)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = outcome ~ age, family = binomial, data = Whickham_smoker)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.0009   0.1337   0.3044   0.6362   1.8457  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(>|z|)    
## (Intercept)  6.71139    0.57702   11.63   <2e-16 ***
## age         -0.11100    0.01054  -10.53   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 639.89  on 581  degrees of freedom
## Residual deviance: 453.72  on 580  degrees of freedom
## AIC: 457.72
## 
## Number of Fisher Scoring iterations: 5
\end{verbatim}

\hypertarget{non-smokers}{%
\paragraph{Non-Smokers}\label{non-smokers}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Whickham_nonsmoker<-}\StringTok{ }\NormalTok{Whickham }\OperatorTok{%>%}\StringTok{ }\KeywordTok{filter}\NormalTok{(smoker}\OperatorTok{==}\StringTok{"No"}\NormalTok{)}
\NormalTok{m3_nonsmoker<-}\KeywordTok{glm}\NormalTok{(outcome}\OperatorTok{~}\NormalTok{age, }\DataTypeTok{data=}\NormalTok{Whickham_nonsmoker, }\DataTypeTok{family=}\NormalTok{binomial)}
\KeywordTok{summary}\NormalTok{(m3_nonsmoker)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm(formula = outcome ~ age, family = binomial, data = Whickham_nonsmoker)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.3983  -0.4609   0.1532   0.4357   1.9283  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(>|z|)    
## (Intercept)  8.169231   0.606600   13.47   <2e-16 ***
## age         -0.133231   0.009953  -13.39   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 911.23  on 731  degrees of freedom
## Residual deviance: 488.96  on 730  degrees of freedom
## AIC: 492.96
## 
## Number of Fisher Scoring iterations: 6
\end{verbatim}

We see similar directions -- negative relationships between age and
survival -- for both smokers and non-smokers. The question that the
interaction term in a regression model with both smokers and non-smokers
helps test is, essentially, is the coefficient for age for non-smokers
(-0.133) statistically significantly steeper than for smokers (-0.111).

\vspace{0.25in}

\textbf{13. Is this model with the interaction term a better fit than
the model with Age alone (Model 0 above), or than the model with just
Smoking alone (Model 1)?}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(lmtest)}
\KeywordTok{lrtest}\NormalTok{(m3,m0)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Likelihood ratio test
## 
## Model 1: outcome ~ age + smoker + age * smoker
## Model 2: outcome ~ age
##   #Df  LogLik Df  Chisq Pr(>Chisq)
## 1   4 -471.34                     
## 2   2 -473.25 -2 3.8255     0.1477
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{lrtest}\NormalTok{(m3,m1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Likelihood ratio test
## 
## Model 1: outcome ~ age + smoker + age * smoker
## Model 2: outcome ~ smoker
##   #Df  LogLik Df  Chisq Pr(>Chisq)    
## 1   4 -471.34                         
## 2   2 -775.56 -2 608.44  < 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\emph{a. What are the null and alternative hypotheses for each of these
tests?}

\(H_0: \beta_2 = \beta_3 = 0\) \(H_A: \beta_i \neq 0\)

\emph{b. What is the test statistic and p-value for each and what does
that mean about the test?}

The difference in log-Likelihood was 3.8, which on the \(\chi^2\)
distribution with 2 degrees of freedom, corresponded to a p=0.14. Thus
we fail to reject the null hypothesis that the model with smoking and
its interaction with age is significantly better fitting model than the
model with age alone.

The difference in log-Likelihood was 608.44, which on the \(\chi^2\)
distribution with 2 degrees of freedom, corresponded to a
p\textless{}0.001. Thus we reject the null hypothesis and conclude that
the model with smoking and its interaction with age is a significantly
better fitting model than the model with smoking alone.

\emph{c. What do these tests tell you about the relationships between
age, smoking, and survival over 20 years in this cohort of women from
Whickham?}

This makes some sense -- smoking itself is not a very strong predictor
of survival above and beyond age. The model with age and the interaction
between age and smoking is a better fit than the simple logistic
regression model with just smoking mostly because age matters so much
for survival.

We would conclude from this that the relationship between age and
survival does not significantly vary by smoking status. And adding
smoking and this interaction term to the mode of just age alone does not
add significant value. Thus, we might choose the simple logistic
regression model for age alone as the best model of those that we
tested.

\end{document}
