---
title: "0. Getting Started"
date: "2020-01-29"
due_date: "2020-01-29"
due_time: "11:59 AM"
menu:
  assignment:
    parent: Assignments
    weight: 1
type: docs
weight: 1
output:
  blogdown::html_page:
    toc: true
editor_options: 
  chunk_output_type: console
---

### Initial Course Administration Tasks
There are a few small, administrative things to get started. These should have done during the first week of class.

1. Read the syllabus
1. Get a copy of [the textbook](https://www.amazon.com/STAT2-Modeling-Regression-Ann-Cannon-ebook-dp-B07K6Y99J3/dp/B07K6Y99J3/ref=mt_kindle?_encoding=UTF8&me=&qid=1579815019) (& see notes about buying the book in the syllabus)
1. Download the [PollEverywhere app](https://www.polleverywhere.com/mobile) to your phone or a device that you'll have with you in the classroom
1. Set up an account with [RStudio Cloud](https://rstudio.cloud/) (easiest via Google with your Smith account). We will not be using the RStudio Cloud exclusively, but we will need to use it at a least a few points during the semester.
1. Join the [course Slack](https://join.slack.com/t/sds291-spring2020/shared_invite/enQtOTI0MzIwMjMwOTE3LTk1MjFmZTA4YjNjZmYxYTU4MTNiYjU3MWFhYTQ4MzNjNDkxYjZjMTE2YjE0N2Q4MmFmZmI2NTE3NTI2MzY2Mjc) and post an animal gif in the channel for your section (Section 01: 1:20-2:35, or Section 02: 2:45 - 4:00pm). If you're new to Slack, look through the Resources section of this page for some more information to get started. 
1. Add a 1-2 songs to [a playlist for our class](https://open.spotify.com/playlist/70l14LCdw5XOAyk1RHeuAO?si=Enp-jrtiSeKWhU4XYueiqg). I like playing music at the beginning of class and during in-class work time (there will be a lot), so add something you'd like to hear. See more [here](https://support.spotify.com/us/article/create-playlists-with-your-friends/) about adding to a collaborative playlist. If you don't have a Spotify account or have trouble adding songs directly to Spotify, just add the song title and artist in this google form.

### Getting started with `R` & Refreshing Statistics

New to `R`? Feeling rusty on your introductory statistics material?*

1. Don't fret -- we'll do this all together, no need to feel like you have to do any prep before class.
1. If you _want_ to practice `R`, especially during the first few weeks of semester when the workload is a little lighter, try the [primers in RStudio Cloud](https://rstudio.cloud/learn/primers), especially the first four (don't worry about iterate or write functions)
1. Take a look back at your intro stats text book, or [this open source textbook](https://drive.google.com/file/d/0B-DHaDEbiOGkRHNndUlBaHVmaGM/edit). You might want to review normal distributions, tests of differences in means (t-tests), ANOVA, and interpretation of p-values and confidence intervals. We'll cover the regression specific material, but those ideas underlie much of regression. Again, I wouldn't stress about this at this point, but a very quick skim could help get the dust off your recall of this material.

*Many former students have had some anxiety coming into the class about the learning curve to learn `R`. I am fully anticipating -- and can empathize with! -- this nervousness. We will talk plenty about how to get going with `R` for those in the class who haven't used it before, with additional resources as we get going. We'll cover what you need in class, but if you want to do some extra practice in the first few weeks of the semester while things are (generally) quiet, it might be useful to do so.
