---
title: "3. Problem set 3"
date: "2020-02-24"
due_date: "2020-02-24"
due_time: "11:59 AM"
menu:
  assignment:
    parent: Problem sets
    weight: 3
type: docs
weight: 3
output:
  blogdown::html_page:
    toc: true
editor_options: 
  chunk_output_type: console
---

# Required

Questions 3.17, 3.22 (2nd Edition) / 3.11 and 3.15 (1st Edition) - and one more question below

## For 3.17:

- Do not use `R` for this problem to fit the regression model or to automatically do the calculations. Use the numbers from the output material in the book.

- B. Calculate a 95% CI where $t^*$ is 1.96. Do not calculate a 90% CI.

## For 3.22:

- Do as stated in the book.

## Additional Question:

We're using the same data as from class this week: a sample of 104 homes in Northampton, MA to see whether being close to the bike trail enhances the value of the home. Specifically, we're looking at the association between square feet (a house's size) and distance from the rail trail with the house's estimated value in 2014. The variables we're using are: 

- `Price2014`: Zillow price estimate from 2014 (in thousands of dollars)
- `Distance`: Distance (in *miles*) to the nearest entry point to the rail trail network
- `Bedrooms`: Number of bedrooms


### a. Fit the simple linear regression model of _Price2014_ on _distance_. Interpret the relationship between _Price2014_ and distance in the context of this problem.

### b. Next fit a multiple linear regression model with _Distance_ and _Bedrooms_. How has the addition of bedrooms changed our estimate of the relationship of distance to _Price2014_? Use both the estimated coefficients and Adjusted $R^2$ in your answer.

### c. Find the 95% Confidence Interval for the distance coefficent from the model in "b" and interpret it in the context of this problem.

### d. Estimate the expected value of two houses, each 0.75 miles from the trail, one with 3 and one with 4 bedrooms. Interpret this value in a sentence.

### e. Estimate the expected value of two houses, each with 2 bedrooms, one that's 0.25 miles and another that's 1.25 miles from the rail trail. Interpret this value in a sentence.

# Submit on Moodle

There is no template for this assignment. You're a pro at making your own RMarkdown files now!

You are expected to knit to pdf. Please allow enough time to resolve any errors before the deadline. 

Use the Homework 1 submission on Moodle for [section 1](https://moodle.smith.edu/course/view.php?id=36873) or [section 2](https://moodle.smith.edu/course/view.php?id=36874). 
